name: Publish to DockerHub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to DockerHub
        run: |
          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          docker image build -t piturriti1/upv-oos-reservations:latest .
          docker push piturriti1/upv-oos-reservations:latest
